Web/ViewModels/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using IDAL.Models;

namespace Web.ViewModels
{
    public class ReportViewModel
    {
        public Employee Employee { get; set; }
        public List<Page> Pages { get; set; }
    }
}

Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BLL.Identity.Models;
using BLL.Services.AlertService;
using BLL.Services.MailingService.Interfaces;
using BLL.Services.PersonageService;
using BLL.Services.TestService;
using BLL.Services.TestService.Interfaces;
using IDAL.Interfaces;
using IDAL.Models;
using Microsoft.AspNet.Identity;
using Web.ViewModels;
using BLL.Services.ReportService;
using IDAL;

namespace Web.Controllers
{
    public class ReportController : BaseController
    {
        private readonly ITestService _testService;
        private readonly ReportPassingManager _reportManager;

        public ReportController(IUnitOfWork uow, ReportPassingManager reportManager, UserManager<IdentityUser, Guid> userManager, PersonManager<Admin> adminManager, PersonManager<Advisor> advisorManager, PersonManager<Employer> employerManager, AlertManager alertManager, ReportPassingManager reportPassingManager, IMailingService mailingService) 
            : base(userManager, adminManager, advisorManager, employerManager, alertManager, reportPassingManager, mailingService)
        {
            _testService = new TestManager(uow);
            _reportManager = reportManager;
        }

        [HttpGet]
        public ViewResult CreateReport()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> AddPages(Page[] pages)
        {
            if (!ModelState.IsValid || pages == null || pages.Length == 0)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Not all pages are valid");

            await _testService.DeleteAllPages(); //deleting old template

            await _testService.AddPages(pages);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpGet]
        public async Task<ActionResult> GetAllPages(Guid? id)
        {
            if (id == null || id.Value == Guid.Empty)
            {
                return RedirectToAction("Index", "Home");
            }

            var pages = await _testService.GetAllPages() 
                ?? new List<Page>();

            var model = new ReportViewModel
            {
                Employee =  await adminManager.GetEmployee(id.Value),
                Pages = pages.OrderBy(p => p.Order).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> SaveReport(FormCollection formCollection)
        {
            var pages = new List<Page>();

            int pageId, questionId;
            int? questionType, lineId, answerId; // for complicated question

            string employeeId = null;

            foreach (var key in formCollection.AllKeys)
            {
                if(key == "EmployeeId")
                {
                    employeeId = formCollection[key];
                    continue;
                }

                _testService.ParseAnswerName(key, out pageId, out questionId, out questionType, out lineId, out answerId);

                var page = pages.FirstOrDefault(p => p.Id == pageId);
                if (page == null)
                {
                    var dbPage = await _testService.GetPageById(pageId);

                    page = new Page
                    {
                        Id = dbPage.Id,
                        Name = dbPage.Name,
                        Order = dbPage.Order,
                        Questions = new List<Question>()
                    };
                }
                else
                {
                    var oldPage = page;
                    pages.Remove(oldPage);
                }
                
                var question = page.Questions.FirstOrDefault(q => q.Id == questionId);
                if (question == null)
                {
                    var dbQuestion = await _testService.GetQuestion(questionId);
                    question = new Question
                    {
                        Id = dbQuestion.Id,
                        QuestionName = dbQuestion.QuestionName,
                        TypeAnswer = dbQuestion.TypeAnswer,
                        PageId = dbQuestion.PageId,
                        Answers = new List<Answer>()
                    };
                }
                else
                {
                    var oldQuestion = question;
                    page.Questions.Remove(oldQuestion);
                }
                
                foreach (var value in formCollection.GetValues(key))
                {
                    var answer = new Answer
                    {
                        Name = value,
                        QuestionId = question.Id
                    };
                    question.Answers.Add(answer);
                }
                
                page.Questions.Add(question);
                pages.Add(page);
            }

            Guid emplId;
            Employee employee;
            if (!Guid.TryParse(employeeId, out emplId) || (employee = await adminManager.GetEmployee(emplId)) == null)
            {
                return View("ReportResult", false);
            }

            var sender = new ReportSender(mailingService, adminManager, employee, pages);

            var result = await sender.SendMailsToRecieversAsync();
            if (result.Succeeded)
            {
                await _reportManager.AddReport(emplId);
            }

            return View("ReportResult", new ReportPassedViewModel
            {
                Passed = result.Succeeded,
                EmployeeId = emplId.ToString()
            });
        }
    }
}

Web/Views/Report/CreateReport.cshtml
@{
    ViewBag.Title = "CreateReport";
}

@section styles {
    <link rel="stylesheet" href="/Content/main.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
}

<div class="innerWrapper">
    <div class="leftPagePanel">
        <button id="btnAddPage" class="btn btn-default" data-target="#myModalPage">Add Page</button>
        <div class="pageContainer">
            <ul class="sortablePages">
                <!--li>
                    <button class="btn btn-default btn-nav">Page1</button>
                </li>
                <li>
                    <button class="btn btn-default btn-nav selectedPage">Page1</button>
                </li-->
            </ul>
        </div>
    </div>
    <div class="container mainGrid">
        <div class="actionBar">
            <!--span class="col-md-1 previewHeader">Preview</span-->
            <button id="btnDeletePage" class="pull-left btn btn-default buttonDeletePage">Delete Page</button>
            <button id="btnAddQuestion" class="btn btn-default pull-right" data-target="#myModal">Add Question</button>

        </div>
        <div id="namePageGrid">
            
        </div>
        <div class="containerQuestions">

            <!-- <div class="wrapperQuestion">
                <img class="deleteQuestion" src="5.1 Report.png">
                <img class="editQuestion" src="pen.png">
                <span class="nameOfQuestion">Name of Question</span>
                <div class="containerAnswers">
                    <div class="radio">
                        <label><input type="radio" name="browser" value="ie"> Internet Explorer</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="browser" value="opera"> Opera</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="browser" value="firefox"> Firefox</label>
                    </div>
                </div>
            </div>

            <div class="wrapperQuestion">
                <img class="deleteQuestion" src="5.1 Report.png">
                <img class="editQuestion" src="pen.png">
                <span class="nameOfQuestion">Комментарий</span>
                <div class="containerAnswers">
                    <textarea class="form-control textareaAnswer" name="comment" rows="3"></textarea>
                </div>
            </div>

            <div class="wrapperQuestion">
                <img class="deleteQuestion" src="5.1 Report.png">
                <img class="editQuestion" src="pen.png">
                <span class="nameOfQuestion">Checkboxes</span>
                <div class="containerAnswers">
                    <div class="checkbox">
                        <label><input type="checkbox" value="">Option 1</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" value="">Option 2</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" value="">Option 3</label>
                    </div>

                </div>
            </div> -->

        </div>
    </div>
    <div class="containerSaveBtn">
        <button id="btnSaveTest" class="btn btn-default">Save</button>
    </div>

</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Question</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid form-group">
                    <div class="row">
                        <span>Name of question:</span>
                    </div>
                    <div id="questionNameWrapper" class="row">
                        <input id="questionName" type="text" class="form-control nameOfQuestion">
                        <span class="nameQuestionError">Field "Name of question" is required</span>
                    </div>
                    <div class="row">
                        <span>Type of answer:</span>
                        <select id="cbTypeAnswers">
                            <option selected="selected" value="Checkboxes">Checkboxes</option>
                            <option value="Radiobuttons">Radiobuttons</option>
                            <option value="Comment">Comment</option>
                            <option value="CompType1">Complicated type 1</option>
                            <option value="CompType2">Complicated type 2</option>
                            <option value="CompType3">Complicated type 3</option>
                            <option value="DatepickerSimple">Datepicker</option>
                            <option value="SingleLine">Single line</option>
                        </select>
                    </div>
                    <div class="row addAnswer">
                        <button id="btnAddAnswer" type="button" class="btn btn-default">Add Answer</button>
                    </div>
                    <div class="row containerAnswersModal">
                        <!--div class="input-group wrapperAnswer">
                            <input type="text" class="form-control">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-default">X</button>
                            </span>
                        </div-->
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="btnMyModalCancel">Cancel</button>
                <button id="btnMyModalOK" type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModalPage" tabindex="-1" role="dialog" aria-labelledby="myModalPageLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalPageLabel">Add Page</h4>
            </div>
            <div class="modal-body">
                <div class="container form-group">
                    <div class="row">
                        <span>Name of page:</span>
                    </div>
                    <div class="row">
                        <input id="pageNameModal" type="text" class="form-control nameOfQuestion">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="btnMyModalPageOK" type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="myModalPageEditName" tabindex="-1" role="dialog" aria-labelledby="myModalPageEditNameLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalPageEditNameLabel">Edit page name</h4>
            </div>
            <div class="modal-body">
                <div class="container form-group">
                    <div class="row">
                        <span>Name of page:</span>
                    </div>
                    <div class="row">
                        <input id="pageEditNameModal" type="text" class="form-control nameOfQuestion">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="btnMyModalPageEditNameOK" type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deletePageModal" tabindex="-1" role="dialog" aria-labelledby="myModalPageLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalPageLabel">Deleting Page!!!</h4>
            </div>
            <div class="modal-body">
                <div class="container form-group">
                    <div class="row">
                        <span>Are you sure what want to delete page?</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="btnDeletePageModalOK" type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteQuestionModal" tabindex="-1" role="dialog" aria-labelledby="myModalPageLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalPageLabel">Deleting Question!!!</h4>
            </div>
            <div class="modal-body">
                <div class="container form-group">
                    <div class="row">
                        <span>Are you sure what want to delete question?</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="btnDeleteQuestionModalOK" type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ajaxResultModal" tabindex="-1" role="dialog" aria-labelledby="myModalPageLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Test template creation result</h4>
            </div>
            <div class="modal-body">
                <div class="container form-group">
                    <div class="row">
                        <span id="ajaxStatsMessage"></span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnAjaxHideModal" type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script type="text/javascript" src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script> <!-- Please, add jQuery UI to project-->
    <script type="text/javascript" src="~/Scripts/loadingoverlay.min.js"></script>
    <script src="~/Scripts/report/core.js"></script>

}

Web/Views/Report/GetAllPages.cshtml
@using Web.Infrastructure.HtmlHelpers
@model Web.ViewModels.ReportViewModel
@{
    ViewBag.Title = "GetAllPages";
}

@section styles {
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <!-- progressbar -->
    <link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="~/Content/jquery.stepProgressBar.css" rel="stylesheet" type="text/css">

    <!-- carousel -->
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css" />
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/jquery.slick/1.5.9/slick-theme.css" />

    <link href="../../Content/carousel.css" rel="stylesheet" type="text/css">
}

@Html.Hidden("PageCounterId", Model.Pages.Count)

<div class="col-md-12 col-centered">
    <div id="progressbar">
    </div>
    @using (Html.BeginForm("SaveReport", "Report", FormMethod.Post))
    {
        @Html.Hidden("EmployeeId", Model.Employee.EmployeeId.ToString())
        <div class="carousel">
            <div class="page text-centered">
                <p>U staat op het punt om een rapport op te stellen voor een werknemer.</p><br />
                <p>
                    U kunt op de pijl rechtsonderin klikken om te starten met het rapport. Wanneer u een pagina heeft ingevuld, kunt u door naar de volgende pagina.
                    Door nogmaals op het pijltje links onderin te klikken, kunt u navigeren naar de vorige pagina's. Onderin het scherm kunt
                    u op de balk uw voortgang bekijken.
                </p><br />
                <p>
                    Wanneer alle vragen zijn beantwoord, krijgt u een overzicht van alle beantwoorde vragen zodat u nogmaals uw vragen kunt controleren.
                    Ten slotte kunt u de rapport opsturen naar Poortwachtersloket.
                </p><br />
                <p><b>Succes met het invullen!</b></p><br />
            </div>
            @foreach (var page in Model.Pages)
            {
                <div class="page">
                    <div class="pageTitle">
                        @page.Order. @page.Name
                    </div>
                    <div class="row">
                        @foreach (var question in page.Questions)
                        {
                            @Html.CreateQuestion(question)
                        }
                    </div>
                </div>
            }
            <div class="page">
                <div class="submitTextBlock col-centered text-centered">
                    <p>Controleer alstublieft of u alle velden heeft ingevuld en druk vervolgens op de rechterpijl om een overzicht van het rapport te weergeven</p>
                </div>
            </div>
            <div class="page">
                <div class="previewHeader col-centered">
                    <div class="title1 text-centered">
                        <p>Poortwachtersloket medewerker rapport</p><br />
                    </div>
                    <div class="title2 text-centered">
                        <p>
                            Dit rapport is opgesteld en ingevuld naar aanleiding van het ziekteverzuim van de heer/mevrouw: <span class="italic">
                                @Model.Employee.FirstName
                            @Model.Employee.Prefix @Model.Employee.LastName
                        </span> werkzaam bij <span class="italic">@Model.Employee.Employer.CompanyName</span>
                    </p>
                </div>
            </div>

            @foreach (var page in Model.Pages)
                {
                <div class="pageTitle col-centered text-centered">
                    <span>@page.Name</span>
                </div>
                    <div class="row">
                        @foreach (var question in page.Questions)
                        {
                            <div class="row">
                                @Html.CreatePreview(question)
                            </div>
                        }
                    </div>
            }
            <div class="submitTextBlock col-centered text-centered">
                <p>Controleer of alle velden zijn ingevuld en druk vervolgens op verzenden.</p>
            </div>
            <div class="col-md-3 col-centered">
                <input type="submit" class="btn btn-warning customBtn" />
            </div>
        </div>
    </div>
    }
</div>



@section scripts {
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.stepProgressBar.js"></script>
    <script src="~/Scripts/report/passReport.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
}

Web/Views/Report/ReportResult.cshtml
@model Web.ViewModels.ReportPassedViewModel
@{
    ViewBag.Title = "Report result";
}

<div class="col-md-5 col-centered addEmployeeSuccessBorderWrapper">
    <span class="addEmployeeSuccessHeader">
    </span>
    <br />
    <br />
    @if (Model.Passed)
    {
        <span>
            Het rapport is succesvol verzonden!
        </span>
    }
    else
    {
        <p>Error occured. Please, try one more time</p>
        @Html.ActionLink("Another try", "GetAllPages", "Report", new { id = Model.EmployeeId }, new { @class = "btn btn-default" })
    }
    <br />
    <br />
    @Html.ActionLink("Terug naar werknemer profiel", "EmployeeInfo", new { id = Model.EmployeeId }, new { @class = "btn btn-default" })
</div>


Web/Views/Report/_QuestionPreview.cshtml
@model IDAL.Models.Question
@{
    string labelId = String.Format("viewp{0}q{1}", Model.PageId, Model.Id);
}
<div class="questionPreview">
    <!--Question-->
    <div class="questionTitle col-md-2">
        <span>@Model.QuestionName</span>
    </div>
    <div class="questionAnswer col-md-10">
        <label id=@labelId></label>
    </div>
</div>